spring:
  profiles:
    ##dev  开发环境   prod 生产环境
    active: dev
  #datasource数据库配置

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc.lob.non_contextual_creation: true

#    日志配置
logging:
  level:
    org:
      hibernate:
        sql: debug

#  spring-shiro安全控制


