server:
  port: 38080

spring:
  datasource:
    url: jdbc:mysql://paydomain.top:3306/jarvis_blog?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
    username: root
    password: MyNewPass4!
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 129.204.172.12
    port: 6379
    password: xk123456
