server:
  port: 8081
spring:
  application:
    name: article-service
  datasource:
    url: jdbc:mysql://localhost:3306/idea-school-teach?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: 730805

mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1001/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1