package com.xieke.test.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     * remarks: 
     *
     * @mbggenerated Thu Jul 26 08:34:39 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_name
     * remarks: 
     *
     * @mbggenerated Thu Jul 26 08:34:39 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.pass_word
     * remarks: 
     *
     * @mbggenerated Thu Jul 26 08:34:39 CST 2018
     */
    private String passWord;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * remarks: 
     * @return the value of user.id
     *
     * @mbggenerated Thu Jul 26 08:34:39 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     * remarks: 
     *
     * @param id the value for user.id
     *
     * @mbggenerated Thu Jul 26 08:34:39 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_name
     *
     * remarks: 
     * @return the value of user.user_name
     *
     * @mbggenerated Thu Jul 26 08:34:39 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_name
     * remarks: 
     *
     * @param userName the value for user.user_name
     *
     * @mbggenerated Thu Jul 26 08:34:39 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.pass_word
     *
     * remarks: 
     * @return the value of user.pass_word
     *
     * @mbggenerated Thu Jul 26 08:34:39 CST 2018
     */
    public String getPassWord() {
        return passWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.pass_word
     * remarks: 
     *
     * @param passWord the value for user.pass_word
     *
     * @mbggenerated Thu Jul 26 08:34:39 CST 2018
     */
    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }
}