[#ftl]
package ${table.packageName};

/**
 * This file is auto generated by Ant & FreeMarker.
 * DO NOT MODIFY IT.All modified content will be lost when next auto generate. 
 * 这个文件是用ANT和FreeMarker自动生成的。
 * 不要修改此文件。所有改动将在下次重新自动生成时丢失。
 */
/**
 * 对应数据库表(${table.name}):${table.remarks}
 */
public class ${table.className} {

	[#list props as prop]
	[#if prop.remarks??]
	/** ${prop.remarks} */
	[/#if]
	private ${prop.javaTypeName} ${prop.propertyName};
	
	[/#list]
	[#list props as prop]
		[#if prop.javaTypeName == 'boolean']
	public void set${prop.propertyName?cap_first}(${prop.javaTypeName} ${prop.propertyName}){
		this.${prop.propertyName} = ${prop.propertyName};
	}
	
	public boolean is${prop.propertyName?cap_first}(){
		return this.${prop.propertyName};
	}
			
		[#else]
	public void set${prop.propertyName?cap_first}(${prop.javaTypeName} ${prop.propertyName}){
		this.${prop.propertyName} = ${prop.propertyName};
	}
	
	public ${prop.javaTypeName} get${prop.propertyName?cap_first}(){
		return this.${prop.propertyName};
	}
			
		[/#if]
	[/#list]
	public String toString(){
		StringBuilder buf = new StringBuilder();
		buf.append("${table.className} [");
	[#list props as prop]
		buf.append("${prop.propertyName}=").append(${prop.propertyName}).append(",");
	[/#list]
		buf.setLength(buf.length()-1);
		buf.append("]");
		return buf.toString();
	}

}
