[#ftl]
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE sqlMap PUBLIC "-//ibatis.apache.org//DTD SQL Map 2.0//EN" "http://ibatis.apache.org/dtd/sql-map-2.dtd" >
<!--
This file is auto generated by Ant & FreeMarker.
DO NOT MODIFY IT.All modified content will be lost when next auto generate.
这个文件是用ANT和FreeMarker自动生成的。
不要修改此文件。所有改动将在下次重新自动生成时丢失。
-->
<sqlMap namespace="${namespace}">
	
	<resultMap class="${fullClassName}" id="${alias}">
	[#list columns as col]
		<result column="${col.fieldName}" property="${col.propertyName}" />
	[/#list]
	</resultMap>
	
	<resultMap class="java.util.HashMap" id="${alias}Map">
	[#list columns as col]
		<result column="${col.fieldName}" property="${col.propertyName}" />
	[/#list]
	</resultMap>
	
	[#if querySingleSQL??]
	<!-- 根据主键查询一条记录 -->
	<select id="querySingle" resultMap="${alias}" [#if paramType??]parameterClass="${paramType}"[/#if]>
		${querySingleSQL}
	</select>
	[/#if]
	
	<!-- 全查询 -->
	<select id="queryFull" resultMap="${alias}">
		${queryFullSQL}
	</select>
	
	<!-- 向数据库增加一条记录 -->
	<insert id="insert">
		<!--
		<selectKey resultClass="int" keyProperty="id" > 
		SELECT SEQ_WSDEFINITION_ID.nextval AS ID FROM DUAL 
		</selectKey>
		-->
		${insertSQL}
	</insert>
	
	[#if updateSQL??]
	<!-- 根据主键查询一条记录 -->
	<update id="update">
		${updateSQL}
	</update>
	[/#if]
	
	[#if deleteSQL??]
	<!-- 根据主键删除一条记录 -->
	<delete id="delete" [#if paramType??]parameterClass="${paramType}"[/#if]>
		${deleteSQL}
	</delete>
	[/#if]
	
	[#if queryPage??]
	<!-- 分页查询 -->
	<select id="queryPage" resultMap="${alias}Map"
		parameterClass="com.erayt.solar2.engine.query.QueryParam">
		<![CDATA[
		${queryPage}
		]]>
	</select>
	[/#if]
	
	<!-- 查询当前表的总记录数 -->
	<select id="queryCount" resultClass="int">
		SELECT COUNT(*) FROM ${tableName}
	</select>
</sqlMap>
 