server:
  port: 80

#配置数据源
spring:
  datasource:
    # 配置数据源类型
    type:
      com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.25.192.171:3306/pocket?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: dqjdda@1996
    # 初始化，最小，最大连接数
    initialSize: 3
    minidle: 3
    maxActive: 18
    # 获取数据库连接等待的超时时间
    maxWait: 60000
    # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM dual

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

#微信小程序登录相关
weixin:
  url: https://api.weixin.qq.com/sns/jscode2session
  appid: wxd888f75e7f48a9aa
  secret: fee4b4eaec23f47c581844f859b2804f

#jwt相关
jwt:
  header: Authorization

