--- 
#k8sv1.18.2
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80


---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: daohang
  name: daohang
  namespace: daohang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daohang
  template:
    metadata:
      labels:
        app: daohang
    spec:
      containers:
      - image: xxx/nginx:v1
        name: daohang
        resources:
          limits:
            cpu: 2000m
            memory: 1Gi
          requests:
            cpu: 1000m
            memory: 1000Mi
      nodeName: k8s-node2
---
apiVersion: v1
kind: Service
metadata:
  name: daohang-svc
  namespace: daohang
  labels:
    app: daohang
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      name: http                                                                      
      nodePort: 30800
  selector:
    app: daohang

# 解析：如上：我这里使用Deployment控制器来运行该镜像,并指定了其运行的节点
#kubectl apply -f daohang.yaml
#kubectl get pod,svc -n daohang
---
