---
apiVersion: v1
kind: Pod
metadata:
  name: counter
spec:
  containers:
  - name: count
    image: busybox
    args: [/bin/sh, -c,
            'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']

#kubectl logs -f counter

---
apiVersion: v1
kind: Pod
metadata:
  name: curl-pod
  namespace: dev
spec:
  containers:
    - name: curl-pd
      image: curlimages/curl
      command:
        - /bin/sh
        - -c
        - tail -f /dev/null
      #command: ['/bin/sh','-ce','tail -f /dev/null']

---
apiVersion: v1
kind: Pod
metadata:
  name: firstapp
  labels:
    app: firstapp
spec:
  containers:
  - name: firstapp
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
--- 
#pod级别的资源清单  kind: Pod
apiVersion: v1
kind: Pod
metadata:
  name: liveness-test
  labels:
    name: default
spec:
  containers:
  - name: liveness-test
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    command: ["/bin/sh","-c","touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 30"]
    livenessProbe:
        exec:
          command: ["test","-e","/tmp/healthy"]
        initialDelaySeconds: 1
        periodSeconds: 3

# kubectl create -f liveness-test.yaml 
# kubectl delete -f liveness-test.yaml

# kubectl get pod -o wide   #可以看到pod重启的次数
# kubectl describe pod/liveness-test

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - name: test-pd
    image: alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    #add keep pod running
    command: [ "/bin/sh", "-ce", "tail -f /dev/null" ]
    volumeMounts:
    - mountPath: /cache
      name: cache-volume 
  volumes:
  - name: cache-volume
    emptyDir: {}
