---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql


#####ngx-pod/svc
--- 
apiVersion: v1
kind: Pod
metadata:
  name: ngx-app
  labels:
    app: nginx
spec:
  containers:
  - name: ngx-app
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
---
#nginxsvc.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
  ports:
  - port: 8080
  - targetPort: 80
  protocol: TCP
  selector:
    app: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: ngx-svc
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
---
