package com.mini.example.bean;

import java.io.Serializable;
import java.util.Date;

import com.mini.jdbc.StrongEntity;
import com.mini.jdbc.annotation.Column;
import com.mini.jdbc.annotation.Entity;
import com.mini.jdbc.utils.EnumClazz.StrategyType;

/**
 * Entity for table 'test.demo' generated by sxjun
 * 
 * @author sxjun
 * @date 2015-06-22 18:19:47
 */
@Entity(table="users", id = { "id" },strategy=StrategyType.UUID)
public class Demo extends StrongEntity implements Serializable {

	public static final long serialVersionUID = 6405509322884392287L;

	/**
	 * 表字段定义静态类
	 */
	public static final class Columns {
		public static final String id = "id";
		public static final String name = "name";
		public static final String password = "password";
		public static final String createTime = "createtime";
		public static final String type = "type";
	}

	/**
	 * 字段属性
	 */
	private String id;
	private String name;
	private String password;
	private Date createTime;
	private Integer type;


	public void setId (String id) {
		this.id = id;
	}
	
	@Column("id")
	public String getId () {
		return this.id;
	}
	
	public void setName (String name) {
		this.name = name;
	}
	
	@Column("name")
	public String getName () {
		return this.name;
	}
	
	public void setPassword (String password) {
		this.password = password;
	}
	
	@Column("password")
	public String getPassword () {
		return this.password;
	}
	
	public void setCreateTime (Date createTime) {
		this.createTime = createTime;
	}
	
	@Column("createtime")
	public Date getCreateTime () {
		return this.createTime;
	}
	
	public void setType (Integer type) {
		this.type = type;
	}
	
	@Column("type")
	public Integer getType () {
		return this.type;
	}

}
