
package cn.kiwipeach.helloworld.client.entity;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldWSImpl", targetNamespace = "http://impl.api.ws.kiwipeach.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldWSImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns cn.kiwipeach.helloworld.client.entity.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://impl.api.ws.kiwipeach.cn/", className = "cn.kiwipeach.helloworld.client.entity.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://impl.api.ws.kiwipeach.cn/", className = "cn.kiwipeach.helloworld.client.entity.GetUserResponse")
    @Action(input = "http://impl.api.ws.kiwipeach.cn/HelloWorldWSImpl/getUserRequest", output = "http://impl.api.ws.kiwipeach.cn/HelloWorldWSImpl/getUserResponse")
    public User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://impl.api.ws.kiwipeach.cn/", className = "cn.kiwipeach.helloworld.client.entity.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://impl.api.ws.kiwipeach.cn/", className = "cn.kiwipeach.helloworld.client.entity.SayHelloResponse")
    @Action(input = "http://impl.api.ws.kiwipeach.cn/HelloWorldWSImpl/sayHelloRequest", output = "http://impl.api.ws.kiwipeach.cn/HelloWorldWSImpl/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cn.kiwipeach.helloworld.client.entity.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListUser", targetNamespace = "http://impl.api.ws.kiwipeach.cn/", className = "cn.kiwipeach.helloworld.client.entity.GetListUser")
    @ResponseWrapper(localName = "getListUserResponse", targetNamespace = "http://impl.api.ws.kiwipeach.cn/", className = "cn.kiwipeach.helloworld.client.entity.GetListUserResponse")
    @Action(input = "http://impl.api.ws.kiwipeach.cn/HelloWorldWSImpl/getListUserRequest", output = "http://impl.api.ws.kiwipeach.cn/HelloWorldWSImpl/getListUserResponse")
    public List<User> getListUser();

}
