spring:
  messages:
    basename: spring,org/springframework/security/messages
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cola-auth?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
  sms:
    login-process-url: /loginBySms
server:
  error:
    include-stacktrace: always
cola:
  sms:
    type: aliyun
  aliyun:
    accessKeyId: 123
    accessKeySecret: 1231
logging:
  level:
    org.springframework.web: debug
