#!/bin/sh
# ----------------------------------------------------------------------------
#  Copyright 2001-2006 The Apache Software Foundation.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ----------------------------------------------------------------------------
#
#   Copyright (c) 2001-2006 The Apache Software Foundation.  All rights
#   reserved.


# resolve links - $0 may be a softlink
PRG="$0"

while [ -h "$PRG" ]; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done

PRGDIR=`dirname "$PRG"`
BASEDIR=`cd "$PRGDIR/.." >/dev/null; pwd`



# OS specific support.  $var _must_ be set to either true or false.
cygwin=false;
darwin=false;
case "`uname`" in
  CYGWIN*) cygwin=true ;;
  Darwin*) darwin=true
           if [ -z "$JAVA_VERSION" ] ; then
             JAVA_VERSION="CurrentJDK"
           else
             echo "Using Java version: $JAVA_VERSION"
           fi
           if [ -z "$JAVA_HOME" ] ; then
             JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Versions/${JAVA_VERSION}/Home
           fi
           ;;
esac

if [ -z "$JAVA_HOME" ] ; then
  if [ -r /etc/gentoo-release ] ; then
    JAVA_HOME=`java-config --jre-home`
  fi
fi

# For Cygwin, ensure paths are in UNIX format before anything is touched
if $cygwin ; then
  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --unix "$JAVA_HOME"`
  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --unix "$CLASSPATH"`
fi

# If a specific java binary isn't specified search for the standard 'java' binary
if [ -z "$JAVACMD" ] ; then
  if [ -n "$JAVA_HOME"  ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
      # IBM's JDK on AIX uses strange locations for the executables
      JAVACMD="$JAVA_HOME/jre/sh/java"
    else
      JAVACMD="$JAVA_HOME/bin/java"
    fi
  else
    JAVACMD=`which java`
  fi
fi

if [ ! -x "$JAVACMD" ] ; then
  echo "Error: JAVA_HOME is not defined correctly." 1>&2
  echo "  We cannot execute $JAVACMD" 1>&2
  exit 1
fi

if [ -z "$REPO" ]
then
  REPO="$BASEDIR"/lib
fi

CLASSPATH=$CLASSPATH_PREFIX:"$BASEDIR"/conf:"$REPO"/cocook-0.0.2.jar:"$REPO"/javassist-3.17.1-GA.jar:"$REPO"/velocity-1.7.jar:"$REPO"/commons-collections-3.2.1.jar:"$REPO"/slf4j-api-1.7.2.jar:"$REPO"/httpclient-0.0.2.jar:"$REPO"/okhttp-3.2.0.jar:"$REPO"/okio-1.6.0.jar:"$REPO"/commons-lang-2.5.jar:"$REPO"/javax.servlet-api-3.0.1.jar:"$REPO"/cos-09May2002.jar:"$REPO"/fastjson-1.2.4.jar:"$REPO"/druid-1.0.18.jar:"$REPO"/jedis-2.1.0.jar:"$REPO"/commons-pool-1.5.5.jar:"$REPO"/postgresql-9.4.1208.jre7.jar:"$REPO"/logback-classic-1.1.3.jar:"$REPO"/logback-core-1.1.3.jar:"$REPO"/guava-15.0.jar:"$REPO"/junit-4.11.jar:"$REPO"/hamcrest-core-1.3.jar:"$REPO"/undertow-core-1.4.4.Final.jar:"$REPO"/jboss-logging-3.2.1.Final.jar:"$REPO"/xnio-api-3.3.6.Final.jar:"$REPO"/xnio-nio-3.3.6.Final.jar:"$REPO"/undertow-servlet-1.4.4.Final.jar:"$REPO"/jboss-servlet-api_3.1_spec-1.0.0.Final.jar:"$REPO"/jboss-annotations-api_1.2_spec-1.0.0.Final.jar:"$REPO"/xyt_api-0.1.jar
EXTRA_JVM_ARGUMENTS="-server -Xmx500M -Xms500M -Xss512k"

# For Cygwin, switch paths to Windows format before running java
if $cygwin; then
  [ -n "$CLASSPATH" ] && CLASSPATH=`cygpath --path --windows "$CLASSPATH"`
  [ -n "$JAVA_HOME" ] && JAVA_HOME=`cygpath --path --windows "$JAVA_HOME"`
  [ -n "$HOME" ] && HOME=`cygpath --path --windows "$HOME"`
  [ -n "$BASEDIR" ] && BASEDIR=`cygpath --path --windows "$BASEDIR"`
  [ -n "$REPO" ] && REPO=`cygpath --path --windows "$REPO"`
fi

nohup "$JAVACMD" $JAVA_OPTS \
  $EXTRA_JVM_ARGUMENTS \
  -classpath "$CLASSPATH" \
  -Dapp.name="xyt-api" \
  -Dapp.pid="$$" \
  -Dapp.repo="$REPO" \
  -Dapp.home="$BASEDIR" \
  -Dbasedir="$BASEDIR" \
  cn.xyt.XYT_API_MAIN \
  -p 7070 -h 0.0.0.0 "$@" >> ../logs/console.log 2>&1 &
