server:
  port: 80
beetl:
  resource-auto-check: true       #热加载beetl模板，开发时候用
  
spring:
 profiles:
   active: dev
 thymeleaf:
   prefix: classpath:/
   suffix: .html
   cache: false #关闭缓存
---
spring:
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/speedy?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      readOnly: false
      connectionTimeout: 60000
      idleTimeout: 60000
      validationTimeout: 3000
      maxLifetime: 60000
      loginTimeout: 5
      maximumPoolSize: 1000
      minimumIdle: 10

