package com.imzdx.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}

	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setAuthorId(java.lang.Long authorId) {
		set("author_id", authorId);
		return (M)this;
	}

	public java.lang.Long getAuthorId() {
		return getLong("author_id");
	}

	public M setDisc(java.lang.String disc) {
		set("disc", disc);
		return (M)this;
	}

	public java.lang.String getDisc() {
		return getStr("disc");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setCategory(java.lang.String category) {
		set("category", category);
		return (M)this;
	}

	public java.lang.String getCategory() {
		return getStr("category");
	}

	public M setUv(java.lang.Long uv) {
		set("uv", uv);
		return (M)this;
	}

	public java.lang.Long getUv() {
		return getLong("uv");
	}

	public M setLike(java.lang.Long like) {
		set("like", like);
		return (M)this;
	}

	public java.lang.Long getLike() {
		return getLong("like");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
