package com.foo.common.base.algorithms;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Auto Generated By IntelliJIdea on 9/18/16.
 */
public class CareerHelper {
    final private static Logger logger = LoggerFactory.getLogger(CareerHelper.class);



    public static int test() {
        logger.info("CareerHelper a");
        return 0;
    }


}
