package com.foo.common.base.algorithms;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Auto Generated By IntelliJIdea on 9/21/16.
 */
public class LevelOneClass {

    public   int x = CareerHelper.test();

    final private static Logger logger = LoggerFactory.getLogger(LevelOneClass.class);

    static {
        logger.info("LevelOneClass static");
    }

    public LevelOneClass( ) {
        logger.info("LevelOneClass construct");
    }
}
