package com.foo.common.base.algorithms;

import com.google.common.primitives.Ints;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Auto Generated By IntelliJIdea on 9/21/16.
 */
public class LevelTwoClass extends LevelOneClass {
    final private static Logger logger = LoggerFactory.getLogger(LevelTwoClass.class);

    {
        logger.info("LevelTwoClass static");
    }

    private static void test() {
        logger.info("LevelTwoClass test");
    }

    public LevelTwoClass() {
        logger.info("LevelTwoClass construct");
    }

    public static void main(String[] args) {
        LevelOneClass one = new LevelTwoClass();
        String a = "aa";
        String b = new String("aa");
        logger.info("{}", Integer.MAX_VALUE + 1 < 1);
//        one = new LevelTwoClass();
        ((LevelTwoClass) null).test();

    }
}
