apiVersion: v1
kind: Pod
metadata:
  name: ngx-app
  labels:
    app: nginx
spec:
  containers:
  - name: ngx-app
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80