server:
    port: 1314

#配置数据源
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8
        username: root
        password: 999999
        driver-class-name: com.mysql.jdbc.Driver

#指定mybatis映射文件的地址
mybatis:
    mapper-locations: classpath:mapper/*.xml

# 打印sql
logging:
    level:
        com.xieke.test.dao : debug