apiVersion: v1
kind: Namespace
metadata:
  name: nginx-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: nginx-2
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: nginx-2
spec:
  selector:
    matchLabels:
      app: busybox
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - name: busybox
        image: busybox
        stdin: true
        tty: true
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-2
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: nginx