server:
  port: 9000
spring:
  datasource:
         driver-class-name: com.mysql.jdbc.Driver
         url: 
         username: 
         password: 
  data:
    mongodb:
      uri: 
      database: 
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
    level:
       com.sise.school.teach : debug