server:
  port: 80
  servlet:
    context-path: /
## spring jdbc配置
spring:
  datasource:
    url: jdbc:mysql://47.111.17.90:3306/jfast?serverTimezone=GMT%2B8&useSSL=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: jxhwly0555
    driver-class-name: com.mysql.cj.jdbc.Driver
  ## 文件上传大小限制
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
file:
  uploadPath: /root/uploads/
mybatis:
  config-location: classPath:mybatis/mybatis-config.xml
  mapper-locations: xml/**/*.xml
logging:
  file: /root/jar/jfast.log
