antdsp: 
   name: antdsp
   version: 0.0.1
   copyrightYear: 2019
   logback: 
      filepath: @antdsp.logback.filepath@
server:
   servlet:
      context-path: /antdsp-api
      session: 
         timeout: 30
   port: 8088
spring:
   datasource:
      type: @antdsp.db.datasource@
      druid: 
         driver-class-name: @antdsp.db.driver@
         url: @antdsp.db.url@
         username: @antdsp.db.username@
         password: @antdsp.db.password@
         initial-size: 10
         max-active: 100
         min-idle: 10
         max-wait: 60000
         pool-prepared-statements: true
         max-pool-prepared-statement-per-connection-siz: 20
         time-between-eviction-runs-millis: 60000
         min-evictable-idle-time-millis: 300000
         test-while-idle: true
         test-on-return: false
         test-on-borrow: false
         stat-view-servlet: 
            enabled: true
            url-patten: /druid/*
            allow: 
         filter: 
            stat: 
               enabled: true
               log-slow-sql: true
               slow-sql-millis: 10000
               merge-sql: true
               
            wall:
               config: 
                  multi-statement-allow: true
   jpa:
      hibernate: 
         ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   application:
      name: antdsp
   aop:
      auto: true   #启动Spring AOP 配置

qiniu:
   accessKey: @qiniu.accessKey@
   secretKey: @qiniu.secretKey@
   bucket: @qiniu.bucket@
    
