package com.imzdx.common.model;

import com.imzdx.common.model.base.BaseFile;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class File extends BaseFile<File> {
    public static final File dao = new File().dao();
}
