server:
  port: 80

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/sys_oa?serverTimezone=UTC&useUnicode=true&useSSL=false&characterEncoding=utf8
      username: root
      password: root
      initialSize: 10
      maxActive: 100
      maxWait: 60000
      minIdle: 5
      filters: stat,wall
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000