server:
  port: 9002
spring:
  application:
    name: tensquare-base
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.2:3306/tensquare_base?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
  rabbitmq:
    host: 192.168.2.2
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.2:6868/eureka/
  instance:
    prefer-ip-address: true
ip: 127.0.1.2222222