server: 
  port: 9008
spring: 
  application:  
    name: tensquare-user #指定服务名
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.2:3306/tensquare_user?characterEncoding=UTF8
    username: root
    password: 123456
  jpa: 
    database: MySQL
    show-sql: true
  redis:
      host: 192.168.2.2
  rabbitmq:
      host: 192.168.2.2
jwt:
  config:
    key: itcast
    ttl: 3600000
eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.2:6868/eureka/
  instance:
    prefer-ip-address: true