url: http://jsonapi.org.cn
safe: true
lsi: false
source: .
destination: ./public
exclude:
  - README.md
  - CNAME
  - .gitignore
  - ./public
  - ./stylesheets/*.scss
markdown: redcarpet
pygments: false
port: 9876

navigation:
- title: 概述
  url: /
- title: 格式
  url: /format/
- title: 扩展
  url: /extending/
- title: 示例
  url: /examples/
- title: FAQ
  url: /faq/
- title: 关于
  url: /about/
