spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://172.20.176.190:8769
server:
  port: 8768

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS