#spring配置
spring:
  profiles:
    active: dev
  application:
    name: 'SmallBun 企业级开发脚手架'
#服务器配置
server:
  port: 8080
#mybats
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.smallbun.**.entity
  #枚举
  type-enums-package: cn.smallbun.**.enums
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ID_WORKER_STR
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      #数据库大写下划线转换
      capital-mode: false
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      #字段验证策略
      insert-strategy: not_empty
      update-strategy: not_empty
      select-strategy: not_empty
    banner: false
  configuration:
    #驼峰下划线转换#驼峰下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: false #开启二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    lazy-loading-enabled: true #设置为true为打开延迟加载 实体类必须加上这个注解@JsonIgnoreProperties(value = {"handler"}) 否则将会报com.fasterxml.jackson.databind.exc.InvalidDefinitionException错误
    aggressive-lazy-loading: false #将积极加载改为消极加载，即延迟加载
    default-fetch-size: 1024 #获取数据默认大小
logging:
  config: classpath:config/logback-spring.xml