//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.16 at 12:33:45 下午 CST 
//


package common.framework.dsb.config;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DSBConfType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DSBConfType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dsb.server.name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dsb.deploy.dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dsb.annotation.bypass.dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dsb.socket.port" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dsb.rmi.server.port" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dsb.server.language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dsb.server.log.dir" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dsb.server.log.name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dsb.server.log.level" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="dsb.server.log.maxfilesize" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cmd.server.port" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cmd.thread.count" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cmd.conn.timeout" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="startupservices" type="{http://www.ideal.sh.cn/dynamic-service-bean}StartupServiesType"/>
 *         &lt;element name="disabledservices" type="{http://www.ideal.sh.cn/dynamic-service-bean}DisabledServiesType"/>
 *         &lt;element name="systemprops" type="{http://www.ideal.sh.cn/dynamic-service-bean}SystemPropsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DSBConfType", propOrder = {
    "dsbServerName",
    "dsbDeployDir",
    "dsbAnnotationBypassDir",
    "dsbSocketPort",
    "dsbRmiServerPort",
    "dsbServerLanguage",
    "dsbServerLogDir",
    "dsbServerLogName",
    "dsbServerLogLevel",
    "dsbServerLogMaxfilesize",
    "cmdServerPort",
    "cmdThreadCount",
    "cmdConnTimeout",
    "startupservices",
    "disabledservices",
    "systemprops"
})
public class DSBConfType {

    @XmlElement(name = "dsb.server.name", required = true)
    protected String dsbServerName;
    @XmlElement(name = "dsb.deploy.dir", required = true)
    protected String dsbDeployDir;
    @XmlElement(name = "dsb.annotation.bypass.dir", required = true)
    protected String dsbAnnotationBypassDir;
    @XmlElement(name = "dsb.socket.port")
    protected int dsbSocketPort;
    @XmlElement(name = "dsb.rmi.server.port")
    protected int dsbRmiServerPort;
    @XmlElement(name = "dsb.server.language", required = true)
    protected String dsbServerLanguage;
    @XmlElement(name = "dsb.server.log.dir", required = true)
    protected String dsbServerLogDir;
    @XmlElement(name = "dsb.server.log.name", required = true)
    protected String dsbServerLogName;
    @XmlElement(name = "dsb.server.log.level")
    protected int dsbServerLogLevel;
    @XmlElement(name = "dsb.server.log.maxfilesize")
    protected int dsbServerLogMaxfilesize;
    @XmlElement(name = "cmd.server.port")
    protected int cmdServerPort;
    @XmlElement(name = "cmd.thread.count")
    protected int cmdThreadCount;
    @XmlElement(name = "cmd.conn.timeout")
    protected long cmdConnTimeout;
    @XmlElement(required = true)
    protected StartupServiesType startupservices;
    @XmlElement(required = true)
    protected DisabledServiesType disabledservices;
    protected List<SystemPropsType> systemprops;

    /**
     * Gets the value of the dsbServerName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsbServerName() {
        return dsbServerName;
    }

    /**
     * Sets the value of the dsbServerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsbServerName(String value) {
        this.dsbServerName = value;
    }

    /**
     * Gets the value of the dsbDeployDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsbDeployDir() {
        return dsbDeployDir;
    }

    /**
     * Sets the value of the dsbDeployDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsbDeployDir(String value) {
        this.dsbDeployDir = value;
    }

    /**
     * Gets the value of the dsbAnnotationBypassDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsbAnnotationBypassDir() {
        return dsbAnnotationBypassDir;
    }

    /**
     * Sets the value of the dsbAnnotationBypassDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsbAnnotationBypassDir(String value) {
        this.dsbAnnotationBypassDir = value;
    }

    /**
     * Gets the value of the dsbSocketPort property.
     * 
     */
    public int getDsbSocketPort() {
        return dsbSocketPort;
    }

    /**
     * Sets the value of the dsbSocketPort property.
     * 
     */
    public void setDsbSocketPort(int value) {
        this.dsbSocketPort = value;
    }

    /**
     * Gets the value of the dsbRmiServerPort property.
     * 
     */
    public int getDsbRmiServerPort() {
        return dsbRmiServerPort;
    }

    /**
     * Sets the value of the dsbRmiServerPort property.
     * 
     */
    public void setDsbRmiServerPort(int value) {
        this.dsbRmiServerPort = value;
    }

    /**
     * Gets the value of the dsbServerLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsbServerLanguage() {
        return dsbServerLanguage;
    }

    /**
     * Sets the value of the dsbServerLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsbServerLanguage(String value) {
        this.dsbServerLanguage = value;
    }

    /**
     * Gets the value of the dsbServerLogDir property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsbServerLogDir() {
        return dsbServerLogDir;
    }

    /**
     * Sets the value of the dsbServerLogDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsbServerLogDir(String value) {
        this.dsbServerLogDir = value;
    }

    /**
     * Gets the value of the dsbServerLogName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDsbServerLogName() {
        return dsbServerLogName;
    }

    /**
     * Sets the value of the dsbServerLogName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDsbServerLogName(String value) {
        this.dsbServerLogName = value;
    }

    /**
     * Gets the value of the dsbServerLogLevel property.
     * 
     */
    public int getDsbServerLogLevel() {
        return dsbServerLogLevel;
    }

    /**
     * Sets the value of the dsbServerLogLevel property.
     * 
     */
    public void setDsbServerLogLevel(int value) {
        this.dsbServerLogLevel = value;
    }

    /**
     * Gets the value of the dsbServerLogMaxfilesize property.
     * 
     */
    public int getDsbServerLogMaxfilesize() {
        return dsbServerLogMaxfilesize;
    }

    /**
     * Sets the value of the dsbServerLogMaxfilesize property.
     * 
     */
    public void setDsbServerLogMaxfilesize(int value) {
        this.dsbServerLogMaxfilesize = value;
    }

    /**
     * Gets the value of the cmdServerPort property.
     * 
     */
    public int getCmdServerPort() {
        return cmdServerPort;
    }

    /**
     * Sets the value of the cmdServerPort property.
     * 
     */
    public void setCmdServerPort(int value) {
        this.cmdServerPort = value;
    }

    /**
     * Gets the value of the cmdThreadCount property.
     * 
     */
    public int getCmdThreadCount() {
        return cmdThreadCount;
    }

    /**
     * Sets the value of the cmdThreadCount property.
     * 
     */
    public void setCmdThreadCount(int value) {
        this.cmdThreadCount = value;
    }

    /**
     * Gets the value of the cmdConnTimeout property.
     * 
     */
    public long getCmdConnTimeout() {
        return cmdConnTimeout;
    }

    /**
     * Sets the value of the cmdConnTimeout property.
     * 
     */
    public void setCmdConnTimeout(long value) {
        this.cmdConnTimeout = value;
    }

    /**
     * Gets the value of the startupservices property.
     * 
     * @return
     *     possible object is
     *     {@link StartupServiesType }
     *     
     */
    public StartupServiesType getStartupservices() {
        return startupservices;
    }

    /**
     * Sets the value of the startupservices property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartupServiesType }
     *     
     */
    public void setStartupservices(StartupServiesType value) {
        this.startupservices = value;
    }

    /**
     * Gets the value of the disabledservices property.
     * 
     * @return
     *     possible object is
     *     {@link DisabledServiesType }
     *     
     */
    public DisabledServiesType getDisabledservices() {
        return disabledservices;
    }

    /**
     * Sets the value of the disabledservices property.
     * 
     * @param value
     *     allowed object is
     *     {@link DisabledServiesType }
     *     
     */
    public void setDisabledservices(DisabledServiesType value) {
        this.disabledservices = value;
    }

    /**
     * Gets the value of the systemprops property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the systemprops property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSystemprops().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SystemPropsType }
     * 
     * 
     */
    public List<SystemPropsType> getSystemprops() {
        if (systemprops == null) {
            systemprops = new ArrayList<SystemPropsType>();
        }
        return this.systemprops;
    }

}
