//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.04.16 at 12:33:45 下午 CST 
//


package common.framework.dsb.config;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the common.framework.dsb.config package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DSBConf_QNAME = new QName("http://www.ideal.sh.cn/dynamic-service-bean", "DSBConf");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: common.framework.dsb.config
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SystemPropsType }
     * 
     */
    public SystemPropsType createSystemPropsType() {
        return new SystemPropsType();
    }

    /**
     * Create an instance of {@link StartupServiesType }
     * 
     */
    public StartupServiesType createStartupServiesType() {
        return new StartupServiesType();
    }

    /**
     * Create an instance of {@link DSBConfType }
     * 
     */
    public DSBConfType createDSBConfType() {
        return new DSBConfType();
    }

    /**
     * Create an instance of {@link DisabledServiesType }
     * 
     */
    public DisabledServiesType createDisabledServiesType() {
        return new DisabledServiesType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DSBConfType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ideal.sh.cn/dynamic-service-bean", name = "DSBConf")
    public JAXBElement<DSBConfType> createDSBConf(DSBConfType value) {
        return new JAXBElement<DSBConfType>(_DSBConf_QNAME, DSBConfType.class, null, value);
    }

}
