server:
  port: 8086
spring:
  application:
    name: auth
  main:
      allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/
    suffix: .html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/
feign:
  client:
    config:
      feignName:
        connectTimeout: 60000
        readTimeout: 60000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

urls: http://www.baidu.com