package com.foo.common.base.algorithms;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Arrays;

import static com.foo.common.base.algorithms.LeetcodeHelper.*;
import static org.junit.Assert.*;

/**
 * Auto Generated By IntelliJIdea on 02/11/2016.
 */
public class LeetcodeHelperTest {

    @Test
    public void test_GetSum() throws Exception {
        logger.info("{}", getSum(10, 10));
    }

    @Test
    public void test_CanWinNim() throws Exception {
        logger.info("{}", canWinNim(8));
    }

    @Test
    public void test_SingleNumber() throws Exception {
        int[] nums = {3, 3, 2, 2, 5, 5, 4, 6, 6};
        logger.info("{}", singleNumber(nums));
    }

    final private static Logger logger = LoggerFactory.getLogger(LeetcodeHelperTest.class);

    @Test
    public void test_TwoSum() throws Exception {
        int[] nums = {2, 8, 10, 10, 4};
        int target = 12;
        System.out.println(Arrays.toString(twoSum(nums, target)));
    }

    @Test
    public void test_FizzBuzz() throws Exception {
        logger.info("{}", fizzBuzz(15));
    }

    @Test
    public void test_ReverseString() throws Exception {
        logger.info("{}",
                reverseString("hello"));
    }

    @Test
    public void test_islandPerimeter() throws Exception {
        int[][] source = {{0, 1, 0, 0}, {1, 1, 1, 0}, {0, 1, 0, 0}, {1, 1, 0, 0}};
        logger.info("{}",
                islandPerimeter(source));
    }

    @Test
    public void test_assignCookies() throws Exception {
        int g[] = {7};
        int s[] = {6,8};
        logger.info("{}",
                assignCookies(g, s));
    }

    @Test
    public void test_it() throws Exception {

        logger.info("{}",
               18%9);
    }

}