package com.foo.common.base.utils;

import com.google.common.collect.ImmutableList;

import java.math.BigDecimal;
import java.util.Collections;

/**
 * Auto Generated By IntelliJIdea on 9/18/16.
 */
public class JvmHelper {
    public static void main(String[] args) {
        Integer i1 = 127;
        Integer i2 = 127;
        System.out.println(i1 == i2);//输出true

        //值大于127时，不会从常量池中取对象
        Integer i3 = 128;
        Integer i4 = 128;

        System.out.println(i3 == i4);//输出false

        String s3="hello";
        String s4="hello";

        System.out.println(s3==s4);//输出true

        "dsad".indexOf("a");

        Collections.reverse(ImmutableList.<String>of("asda"));

        BigDecimal a = new BigDecimal("123");
        BigDecimal b = new BigDecimal("123");
        a.multiply(b).setScale(2, BigDecimal.ROUND_HALF_UP) ;

    }
}
