sudo: false
language: java
script: mvn clean package -Dmaven.test.skip=true
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
# whitelist
branches:
  only:
    - master
    - develop
notifications:
  email: false
before_install:
  - export TZ=Asia/Shanghai