server:
  port: 8899
spring:
  application:
    name: gateway



ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  SocketTimeout: 600000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeout-in-milliseconds: 3000

#ZuulProperties
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  routes:
    auth-server:
      serviceId: auth
      sensitiveHeaders:
      path: /auth/**
    web-client-server:
      serviceId: web
      sensitiveHeaders:
      url: http://localhost:8087
      path: /web/**
    client-one-server:
      serviceId: client-one
      sensitiveHeaders:
      path: /client-one/**
  add-proxy-headers: true
  servlet-path: /



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8085/eureka/
