
package cn.kiwipeach.helloword.client.url;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldWSImpl", targetNamespace = "http://impl.api.ws.kiwipeach.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldWSImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://impl.api.ws.kiwipeach.cn/", className = "cn.kiwipeach.helloword.client.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://impl.api.ws.kiwipeach.cn/", className = "cn.kiwipeach.helloword.client.SayHelloResponse")
    @Action(input = "http://impl.api.ws.kiwipeach.cn/HelloWorldWSImpl/sayHelloRequest", output = "http://impl.api.ws.kiwipeach.cn/HelloWorldWSImpl/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
