apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: elasticsearch
spec:
  replicas: 1
  serviceName:
    es-single
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - env:
        - name: discovery.type
          value: single-node
        - name: cluster.name
          value: docker-cluster
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.3
        name: elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: esdata
      #restartPolicy: Always
      volumes:
      - name: esdata
        hostPath:
          path: /tmp/esdata  #chmod -R 777 /tmp/esdata   //deny access write
          type: DirectoryOrCreate

#  volumeClaimTemplates:
#  - metadata:
#      name: esdata
#    spec:
#      accessModes: ["ReadWriteOnce"]
#      volumeMode: Filesystem
#      resources:
#        requests:
#          storage: 1Gi
#      storageClassName: szy-cloud-nfs-1

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: elasticsearch
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
    nodePort: 30001
  - name: "9300"
    port: 9300
    targetPort: 9300
    nodePort: 30002
  selector:
    app: elasticsearch
  type: NodePort