spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://localhost:3306/crab?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 1q2w3e4r
