spring:
  profiles:
    include: authority,framework
  datasource:
    data: classpath:/import.sql
    url: jdbc:mysql://localhost:3306/framework?characterEncoding=UTF-8&useUnicode=true&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    "cn.gson.framework.model.mapper": debug

mybatis-plus:
  type-aliases-package: cn.gson.framework.model.mapper
  configuration:
    call-setters-on-nulls: true
  mapper-locations:
    - classpath:/mappers/*Mapper.xml
