
package cn.kiwipeach.client.first;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorldWS", targetNamespace = "http://api.ws.kiwipeach.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorldWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns cn.kiwipeach.client.first.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://api.ws.kiwipeach.cn/", className = "cn.kiwipeach.client.first.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://api.ws.kiwipeach.cn/", className = "cn.kiwipeach.client.first.GetUserResponse")
    public User getUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns cn.kiwipeach.client.first.GetMapUserResponse.Return
     */
    @WebMethod
    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "getMapUser", targetNamespace = "http://api.ws.kiwipeach.cn/", className = "cn.kiwipeach.client.first.GetMapUser")
    @ResponseWrapper(localName = "getMapUserResponse", targetNamespace = "http://api.ws.kiwipeach.cn/", className = "cn.kiwipeach.client.first.GetMapUserResponse")
    public cn.kiwipeach.client.first.GetMapUserResponse.Return getMapUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://api.ws.kiwipeach.cn/", className = "cn.kiwipeach.client.first.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://api.ws.kiwipeach.cn/", className = "cn.kiwipeach.client.first.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cn.kiwipeach.client.first.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListUser", targetNamespace = "http://api.ws.kiwipeach.cn/", className = "cn.kiwipeach.client.first.GetListUser")
    @ResponseWrapper(localName = "getListUserResponse", targetNamespace = "http://api.ws.kiwipeach.cn/", className = "cn.kiwipeach.client.first.GetListUserResponse")
    public List<User> getListUser();

}
